# Generated by Django 3.0.8 on 2020-07-24 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('stockOnHand', models.IntegerField(blank=True)),
                ('minimumStock', models.IntegerField(blank=True)),
                ('reorderQtys', models.IntegerField(blank=True)),
                ('boxSize', models.IntegerField(blank=True)),
                ('leadtime', models.CharField(max_length=50)),
                ('weight', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('accountNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartSupplierModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartsApp.PartModel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartsApp.SupplierModel')),
            ],
        ),
        migrations.CreateModel(
            name='PartCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PartsApp.PartModel')),
            ],
        ),
    ]
