# Generated by Django 3.0.8 on 2020-07-24 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('stockonhand', models.IntegerField(blank=True)),
                ('minimumstock', models.IntegerField(blank=True)),
                ('reorderqtys', models.IntegerField(blank=True)),
                ('boxsize', models.IntegerField(blank=True)),
                ('leadtime', models.CharField(max_length=50)),
                ('weight', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('customeraccountnumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartSuppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred', models.BooleanField(default=False)),
                ('partnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartsApp.PartsList')),
                ('partsupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartsApp.Suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='PartComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PartsApp.PartsList')),
            ],
        ),
    ]
