# Generated by Django 3.0.8 on 2020-08-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartmodel',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partmodel',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
