# Generated by Django 3.0.8 on 2020-09-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartmodel',
            name='partNumber',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partmodel',
            name='partNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
