# Generated by Django 3.0.8 on 2021-08-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrdersApp', '0006_auto_20201107_1524'),
        ('PartsApp', '0002_auto_20201019_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartmodel',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='WorkOrdersApp.TaskModel'),
        ),
        migrations.AddField(
            model_name='partmodel',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WorkOrdersApp.TaskModel'),
        ),
    ]
