# Generated by Django 3.0.8 on 2021-08-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0009_instruction'),
        ('PartsApp', '0003_auto_20210823_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpartmodel',
            name='task',
        ),
        migrations.RemoveField(
            model_name='partmodel',
            name='task',
        ),
        migrations.AddField(
            model_name='historicalpartmodel',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ActivitiesApp.GroupModel'),
        ),
        migrations.AddField(
            model_name='partmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ActivitiesApp.GroupModel'),
        ),
    ]
