# Generated by Django 3.0.8 on 2020-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
                ('workCenter', models.CharField(choices=[('PK', 'Picking'), ('LC', 'Lazer Cutting'), ('PC', 'Powder Coating'), ('ZN', 'Zinc Coating'), ('HT', 'Heat Treatment & Shot Peening'), ('RS', 'Brobo Rotary Saw'), ('SK', 'Shakeout'), ('FD', 'Sheet Metal Folding')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskActivityModel',
        ),
    ]
