# Generated by Django 3.0.8 on 2020-09-13 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='workCenter',
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='workCenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ActivitiesApp.WorkCenterTypes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalactivitymodel',
            name='workCenter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ActivitiesApp.WorkCenterTypes'),
        ),
    ]
