# Generated by Django 3.0.8 on 2020-08-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTriggerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completedGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_group', to='ActivitiesApp.GroupModel')),
                ('triggerGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_group', to='ActivitiesApp.GroupModel')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityTriggerModel',
        ),
    ]
