# Generated by Django 3.0.8 on 2020-09-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0002_auto_20200824_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupTriggerModel',
        ),
    ]
