# Generated by Django 3.0.8 on 2020-08-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0002_auto_20200818_1909'),
        ('WorkOrdersApp', '0002_auto_20200818_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskModel',
        ),
        migrations.AddField(
            model_name='groupactivitymodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ActivitiesApp.ActivityModel'),
        ),
        migrations.AddField(
            model_name='groupactivitymodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ActivitiesApp.GroupModel'),
        ),
    ]
