# Generated by Django 3.0.8 on 2020-08-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0004_auto_20200818_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='workCenter',
        ),
    ]
