# Generated by Django 3.0.8 on 2020-10-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0004_auto_20201021_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypartmodel',
            name='location',
            field=models.TextField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactivitypartmodel',
            name='location',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
