# Generated by Django 3.0.8 on 2020-08-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0005_remove_groupmodel_workcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkCenterTypes',
        ),
    ]
