# Generated by Django 3.0.8 on 2020-08-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0006_delete_workcentertypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenterTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workCenter', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='workCenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ActivitiesApp.WorkCenterTypes'),
            preserve_default=False,
        ),
    ]
