# Generated by Django 3.0.8 on 2020-08-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0007_auto_20200818_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workcentertypes',
            old_name='workCenter',
            new_name='wcType',
        ),
    ]
