# Generated by Django 3.0.8 on 2020-12-04 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0008_auto_20201107_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActivitiesApp.ActivityModel')),
            ],
        ),
    ]
