# Generated by Django 3.0.8 on 2020-09-13 04:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0002_auto_20200913_1239'),
        ('WorkOrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaskpartsmodel',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskpartsmodel',
            name='task',
        ),
        migrations.CreateModel(
            name='TaskActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishTime', models.DateTimeField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ActivitiesApp.ActivityModel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WorkOrdersApp.TaskModel')),
            ],
        ),
        migrations.AddField(
            model_name='historicaltaskpartsmodel',
            name='activity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='WorkOrdersApp.TaskActivityModel'),
        ),
        migrations.AddField(
            model_name='taskpartsmodel',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WorkOrdersApp.TaskActivityModel'),
        ),
    ]
