# Generated by Django 3.0.8 on 2020-10-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivitymodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.TaskModel'),
        ),
        migrations.AlterField(
            model_name='taskpartsmodel',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.TaskActivityModel'),
        ),
        migrations.AlterField(
            model_name='taskpartsmodel',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.TaskModel'),
        ),
    ]
