# Generated by Django 3.0.8 on 2020-08-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivitiesApp', '0002_auto_20200818_1909'),
        ('WorkOrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='task',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ActivitiesApp.GroupModel'),
            preserve_default=False,
        ),
    ]
