# Generated by Django 3.0.8 on 2020-09-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskpartsmodel',
            name='increment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskpartsmodel',
            name='increment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
