# Generated by Django 3.0.8 on 2020-11-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrdersApp', '0002_auto_20201012_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskpartsmodel',
            name='serial',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskpartsmodel',
            name='serial',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
