# Generated by Django 3.0.8 on 2020-11-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrdersApp', '0003_auto_20201107_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskpartsmodel',
            name='extra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaskpartsmodel',
            name='order',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskpartsmodel',
            name='extra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskpartsmodel',
            name='order',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
