# Generated by Django 3.0.8 on 2020-11-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrdersApp', '0004_auto_20201107_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaskpartsmodel',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='taskpartsmodel',
            name='extra',
        ),
        migrations.AlterField(
            model_name='historicaltaskpartsmodel',
            name='order',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='taskpartsmodel',
            name='order',
            field=models.IntegerField(default=100000),
        ),
    ]
