# Generated by Django 3.0.8 on 2020-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrdersApp', '0005_auto_20201107_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskpartsmodel',
            name='extra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskpartsmodel',
            name='extra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaskpartsmodel',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taskpartsmodel',
            name='order',
            field=models.IntegerField(),
        ),
    ]
